### PR TITLE
Change safe.directory after git init

### PR DESCRIPTION
**Pull request by migagi**
Hi,
I changed this line:
git config --global --add safe.directory "${PWD}"

After git init, with this the GitHub action works perfec.

Thanks

### CODE REVIEW

**Comment by migagi** [comment]
I changed this line:
git config --global --add safe.directory "${PWD}"

After git init

Thanks

**Comment by benmatselby** [comment]
Hey there, thank you for this @migagi 

Could you explain the issues you were seeing, and how this resolves it please?

**Comment by migagi** [comment]
Hi,

In github action, every step is ok less in Hugo deploy pages step produce this error:

-------------------+-----
  Pages            |  7  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  1  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 48 ms
CNAME set to migagi.github.io, creating file CNAME
Committing the site to git and pushing
Initialized empty Git repository in /github/workspace/public/.git/
Getting hash for base repository commit
_**fatal: detected dubious ownership in repository at '/github/workspace/public'**_
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace/public
--------------------
The solution for this is move "git config --global --add safe.directory "${PWD}"" after git init

**Review by benmatselby — APPROVED** [review]
Makes perfect sense, thank you @migagi

**Pull request merged**
