### PR TITLE
fix: Add golang to docker image installation

### LINKED ISSUE #38: failed to download modules: exec: "go"
Hi,

I've been using this action for a while, following the [Tutorial](https://www.jameswright.xyz/post/deploy-hugo-academic-using-githubio/). But after updating to a newer version of Wowchemy, I'm getting this error:

```
Error: failed to download modules: exec: "go": executable file not found in $PATH
```

I tried to install go in many different ways, for instance:

```
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.x
```

But the error persists.

Do you have any idea about how to solve it?

### PR DESCRIPTION
**Pull request by jrwrigh**
- Add `golang` to the docker image installation

Resolves #38

### CODE REVIEW

**Comment by benmatselby** [comment]
Thanks for this @jrwrigh. Can you give me a little time on this. I think I'd prefer it if we could configure:

- If Go is installed - For example, I don't need it, so installing it increases build time for those that don't need it.
- What version of Go is installed. I would imagine this version of Go is quite old?

**Comment by jrwrigh** [comment]
> * If Go is installed - For example, I don't need it, so installing it increases build time for those that don't need it.
> * What version of Go is installed. I would imagine this version of Go is quite old?

Completely agree on both points; that's why I was originally trying to get https://github.com/actions/setup-go to work since it would achieve both of those things.

On that, I believe I figured out why it wasn't [working before](https://github.com/benmatselby/hugo-deploy-gh-pages/issues/38#issuecomment-999263568). The https://github.com/actions/setup-go installs `go` into the GitHub Ubuntu container*, whereas this GHA creates a nested Docker container to run `hugo` in. So the `$GOROOT` variable was being passed into the nested Docker, but the nested Docker could not access the actual path.

I am unfortunately pretty ignorant in how Docker works, so I'm not sure how to edit the Dockerfile such that the path in `$GOROOT` is made available inside the GHA Docker container. Additionally, whatever potential solution for that would need to know what to do when `$GOROOT` is not set.

**Assuming GHA also runs on containers. I am not sure on the exact workings of GHA, but I believe the above is still true*

**Comment by benmatselby** [comment]
@jrwrigh 

Hey.. I've knocked out https://github.com/benmatselby/hugo-deploy-gh-pages/pull/42. If you have time, could you test this to see if this meets your requirements please?

**Comment by jrwrigh** [comment]
Superseded by #42

**Pull request closed without merging**
